# Generated by Django 2.1.5 on 2019-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectorhit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_info',
            name='dirname',
            field=models.CharField(max_length=256, null=True, verbose_name='CT文件存储路径'),
        ),
    ]
