# Generated by Django 2.1.5 on 2019-11-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectorhit', '0002_ct_info_dirname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_info',
            name='is_pet',
            field=models.BooleanField(default=0, verbose_name='是否是PET图像'),
        ),
        migrations.AddField(
            model_name='ct_info',
            name='specify_id',
            field=models.CharField(max_length=256, null=True, verbose_name='specify_id'),
        ),
        migrations.AlterField(
            model_name='ct_info',
            name='file_name',
            field=models.CharField(max_length=256, verbose_name='CT文件名(压缩)'),
        ),
    ]
