# Generated by Django 2.1.5 on 2019-12-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectorhit', '0003_auto_20191126_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_info',
            name='has_intered',
            field=models.IntegerField(default=0, verbose_name='是否已经插值过'),
        ),
    ]
