# Generated by Django 2.1.5 on 2019-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.IntegerField(verbose_name='pet ct id')),
                ('date', models.FloatField(verbose_name='date result')),
                ('live', models.FloatField(verbose_name='live result')),
            ],
        ),
    ]
