# Generated by Django 2.1.5 on 2019-11-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(verbose_name='医生ID')),
                ('patient_id', models.IntegerField(verbose_name='病人ID')),
                ('patient_symptom', models.CharField(max_length=256, null=True, verbose_name='患者症状')),
                ('CTURL', models.CharField(max_length=256, null=True, verbose_name='CT图像地址')),
                ('AIResult', models.CharField(max_length=256, null=True, verbose_name='算法诊断图像地址')),
                ('DiagResult', models.CharField(max_length=256, null=True, verbose_name='医生诊断结果')),
                ('DiagTime', models.DateTimeField(verbose_name='医生诊断时间')),
                ('DiagRemark', models.CharField(max_length=256, null=True, verbose_name='诊断的图片列表')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=64, null=True, verbose_name='医生姓名')),
                ('doc_birth', models.DateField(null=True, verbose_name='医生生日')),
                ('doc_sex', models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='医生性别')),
                ('doc_depart', models.CharField(max_length=64, null=True, verbose_name='医生部门')),
                ('doc_hospital', models.CharField(max_length=64, null=True, verbose_name='所属医院')),
                ('doc_tel', models.CharField(max_length=32, null=True, verbose_name='联系电话')),
                ('doc_description', models.CharField(max_length=256, null=True, verbose_name='个人简介')),
                ('inform_time', models.DateField(default=django.utils.timezone.now, verbose_name='提醒时间')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是管理员')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=64, verbose_name='病人姓名')),
                ('patient_doc', models.IntegerField(verbose_name='主治医师ID')),
                ('patient_birth', models.DateField(default='1970-01-01', verbose_name='病人生日')),
                ('patient_sex', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='病人性别')),
                ('patient_past_history', models.CharField(max_length=256, null=True, verbose_name='以往病史')),
                ('patient_tel', models.CharField(max_length=32, null=True, verbose_name='联系电话')),
                ('patient_address', models.CharField(max_length=256, null=True, verbose_name='病人住址')),
                ('patient_remark', models.CharField(max_length=256, null=True, verbose_name='病人备注')),
                ('patient_add_time', models.DateTimeField(null=True, verbose_name='添加病人时间')),
            ],
        ),
    ]
